const projects = [
    {name: 'Post It', desc:'Twitter clone in process, so far you can log in and edit your user profile. Soon you will be able to publish content and see the content of others.', code: 'https://github.com/nicoprten/post_it', deploy:'https://post-it-mu.vercel.app/', img:'https://i.ibb.co/QkZHsZF/Sin-t-tulo.png'},
    {name: 'Cinema Time', desc:'Group development using agile methodologies. Development of scalable components with clean code, defining an aesthetic for the web.', code: 'https://github.com/AlannV/PGRUPAL', deploy:'https://estudioda.ar/cinema/', img:'https://i.ibb.co/hc5156Y/cinema-time-proyect.jpg'},
    {name: 'Videogames', desc:'Game browser using React, Redux, SASS for the frontend and Express, PostgreSQL and Sequelize for the backend.', code: 'https://github.com/nicoprten/PI-Videogames', deploy:'https://pi-videogames-blue.vercel.app/', img:'https://i.ibb.co/WBwTg76/videogames-proyect.jpg'},
    {name: 'IMDB App', desc:'Movie search engine to add them to your favorites list, for the design I copied 100% the IMDb page.', code: 'https://github.com/nicoprten/np-imdb-movies-app', deploy:'https://np-imdb-movies-app.vercel.app/', img:'https://i.ibb.co/R66gxc0/prten-movies-proyect.jpg'},
    {name: 'To Do App', desc:'Task list where you can cross out the tasks you have already done, move the order of the tasks, etc.', code: 'https://github.com/nicoprten/NP-S-TODO-LIST', deploy:'https://np-s-todo-list.vercel.app/', img: 'https://i.ibb.co/Lt30ywd/todo-list-proyect.jpg'},
    {name: 'Web Layout', desc:'Pixel-perfect web layout, I did it as part of a challenge for a company.', code: 'https://github.com/nicoprten/challenge-naiades-maquetador-web', deploy:'https://nicolas-prtenjaca-challenge-naiades.vercel.app/', img:'https://i.ibb.co/rbVWtL8/web-layout-proyect.jpg'},
    {name: 'Who´s That Pokemon', desc:'The classic game of guessing which pokemon it is by seeing only its shape, if you guess it, the image of the pokemon will be shown.', code: 'https://github.com/nicoprten/whos_that_pokemon', deploy:'https://nicoprten.github.io/whos_that_pokemon/', img:'https://i.ibb.co/pQFjDS3/guess-pokemon-proyect.jpg'}
];


export default projects;